// Three clean template systems derived from the downloaded demo sites.
function templateDesignCSS() {
  return `
  .layout-salon,.layout-garden,.layout-electric{font-size:16px}.layout-salon .container,.layout-garden .container,.layout-electric .container{width:min(1180px,calc(100% - 64px))}.layout-salon .section,.layout-garden .section,.layout-electric .section{padding:88px 0}.layout-salon .button,.layout-garden .button,.layout-electric .button{min-height:0;font-family:var(--heading);font-size:13px;letter-spacing:.05em}

  /* Modern Salon — Muse Hull's quiet editorial pacing. */
  .layout-salon .site-header{height:90px;background:var(--header);border-bottom:1px solid var(--line);backdrop-filter:none}.layout-salon .brand{font-size:27px;text-transform:lowercase;letter-spacing:-.06em}.layout-salon .nav{gap:28px;font-family:var(--heading);font-size:11px;letter-spacing:.12em;text-transform:uppercase}.layout-salon .nav .button,.layout-salon .header-action{background:var(--ink);border-color:var(--ink);border-radius:999px;padding:12px 20px}.layout-salon .hero{padding-top:90px}.layout-salon .brand-scene{width:min(1100px,88%);margin:auto;aspect-ratio:16/8;object-fit:contain}.layout-salon .hero-copy{position:static!important;background:var(--bg)!important;padding:58px 24px 72px;text-align:center}.layout-salon .hero-copy .inner{max-width:750px}.layout-salon .hero-title{font-size:clamp(46px,6vw,78px)!important;line-height:1.04!important;margin:16px auto 26px;color:var(--ink)!important}.layout-salon .hero-actions{justify-content:center}.layout-salon .hero-actions .button{background:var(--ink)!important;border-color:var(--ink)!important;border-radius:999px}.layout-salon .hero-actions .secondary{background:transparent!important;color:var(--ink)!important;border:0!important;border-bottom:1px solid var(--ink)!important;border-radius:0;padding:10px 0}.layout-salon .section-heading h2{font-size:clamp(38px,4.5vw,62px);font-weight:600}.layout-salon .service-grid{gap:22px}.layout-salon .service-card{border:0;border-radius:0;background:var(--card);box-shadow:none}.layout-salon .service-card:hover{transform:none;box-shadow:none}.layout-salon .card-picture{aspect-ratio:4/5;border-radius:4px}.layout-salon .card-content{padding:18px 0}.layout-salon .card-content h3{font-size:28px}.layout-salon .card-foot{border:0;padding-top:4px;color:var(--ink)}.layout-salon .review-section{background:var(--surface)}.layout-salon .reviews{gap:0;border-top:1px solid var(--line)}.layout-salon .review-card,.layout-salon .review-card:first-child{border:0;border-radius:0;border-bottom:1px solid var(--line);background:transparent;padding:30px}.layout-salon .gallery{gap:18px}.layout-salon .gallery-demo,.layout-salon .gallery-demo:first-child,.layout-salon .gallery-demo:nth-child(6){grid-column:auto;aspect-ratio:4/5;border-radius:4px}.layout-salon .gallery-demo:nth-child(2),.layout-salon .gallery-demo:nth-child(5){margin-top:48px}.layout-salon .closing{background:var(--ink);color:var(--on-accent)}.layout-salon .closing .button{background:var(--card);color:var(--ink);border-color:var(--card);border-radius:999px}

  /* Garden Services — MGS Beverley's image-forward local service site. */
  .layout-garden .site-header{height:78px;background:var(--header);border-bottom:3px solid var(--accent);backdrop-filter:none;box-shadow:0 2px 12px color-mix(in srgb,var(--ink) 10%,transparent)}.layout-garden .brand{font-size:22px}.layout-garden .nav{font-size:12px}.layout-garden .nav .button,.layout-garden .header-action{border-radius:999px;box-shadow:0 6px 16px color-mix(in srgb,var(--accent) 25%,transparent)}.layout-garden .hero{margin-top:78px;background:var(--surface);overflow:hidden}.layout-garden .brand-scene{width:100%;height:min(680px,78vh);aspect-ratio:auto;object-fit:contain}.layout-garden .hero-copy{position:static!important;background:var(--surface)!important;padding:52px 0 62px}.layout-garden .hero-copy .inner{width:min(1180px,calc(100% - 64px))}.layout-garden .hero-title{font-size:clamp(48px,6vw,80px)!important;max-width:18ch!important}.layout-garden .hero-actions .button{border-radius:999px}.layout-garden .hero-actions .secondary{background:transparent!important;color:var(--ink)!important}.layout-garden .section-heading h2{font-size:clamp(42px,5vw,68px)}.layout-garden .service-grid{gap:22px}.layout-garden .service-card{border:1px solid var(--line);border-radius:14px;background:var(--card);box-shadow:0 8px 24px color-mix(in srgb,var(--ink) 8%,transparent)}.layout-garden .card-picture{aspect-ratio:4/3}.layout-garden .card-content h3{font-size:29px}.layout-garden .review-section{background:var(--ink)}.layout-garden .review-section h2,.layout-garden .review-section blockquote{color:var(--on-accent)}.layout-garden .review-section p{color:color-mix(in srgb,var(--on-accent) 75%,transparent)}.layout-garden .review-card,.layout-garden .review-card:first-child{background:color-mix(in srgb,var(--on-accent) 8%,transparent);border:1px solid color-mix(in srgb,var(--on-accent) 18%,transparent);color:var(--on-accent)}.layout-garden .gallery{gap:14px}.layout-garden .gallery-demo{border-radius:10px}.layout-garden .closing{background:var(--accent)}.layout-garden .closing .button{background:var(--card);border-color:var(--card);color:var(--ink);border-radius:999px}

  /* Local Trades — Brian Griffin's clear red-accent hierarchy. */
  .layout-electric .site-header{height:76px;background:var(--header);border-bottom:3px solid var(--accent);backdrop-filter:none;box-shadow:0 2px 10px color-mix(in srgb,var(--ink) 8%,transparent)}.layout-electric .brand{font-size:21px;font-weight:800}.layout-electric .nav{font-size:12px}.layout-electric .nav .button,.layout-electric .header-action{border-radius:999px;padding:11px 18px}.layout-electric .hero{padding-top:76px;background:var(--surface)}.layout-electric .brand-scene{width:100%;height:clamp(300px,44vw,570px);aspect-ratio:auto;object-fit:contain}.layout-electric .hero-copy{position:static!important;background:var(--surface)!important;padding:34px 24px 44px;text-align:center;border-bottom:1px solid var(--line)}.layout-electric .hero-copy .inner{max-width:760px}.layout-electric .hero-title{font-size:clamp(40px,5vw,66px)!important;margin:9px auto 20px;color:var(--ink)!important}.layout-electric .hero-actions{justify-content:center}.layout-electric .hero-actions .button{border-radius:6px}.layout-electric .hero-actions .secondary{background:transparent!important;border:2px solid color-mix(in srgb,var(--ink) 35%,transparent)!important;color:var(--ink)!important}.layout-electric .section-heading h2{font-size:clamp(40px,4.6vw,62px);font-weight:800}.layout-electric .service-grid{gap:16px}.layout-electric .service-card{border:1px solid var(--line);border-radius:6px;background:var(--card);box-shadow:none}.layout-electric .service-card:hover{transform:translateY(-3px);box-shadow:0 12px 26px color-mix(in srgb,var(--ink) 8%,transparent)}.layout-electric .card-picture{aspect-ratio:16/10}.layout-electric .card-content h3{font-size:28px;font-weight:800}.layout-electric .review-section{background:var(--ink)}.layout-electric .review-section h2,.layout-electric .review-section blockquote{color:var(--on-accent)}.layout-electric .review-section p{color:color-mix(in srgb,var(--on-accent) 75%,transparent)}.layout-electric .review-card,.layout-electric .review-card:first-child{background:color-mix(in srgb,var(--on-accent) 8%,transparent);border:1px solid color-mix(in srgb,var(--on-accent) 20%,transparent);color:var(--on-accent)}.layout-electric .gallery{gap:12px}.layout-electric .gallery-demo{border-radius:4px}.layout-electric .closing{background:var(--accent)}.layout-electric .closing .button{background:var(--ink);border-color:var(--ink);border-radius:6px}

  @media(max-width:760px){.layout-salon .container,.layout-garden .container,.layout-electric .container{width:calc(100% - 36px)}.layout-salon .section,.layout-garden .section,.layout-electric .section{padding:62px 0}.layout-salon .nav,.layout-garden .nav,.layout-electric .nav{display:none}.layout-salon .header-action,.layout-garden .header-action,.layout-electric .header-action{display:inline-flex}.layout-salon .menu-toggle,.layout-garden .menu-toggle,.layout-electric .menu-toggle{display:flex}.layout-salon .mobile-nav,.layout-garden .mobile-nav,.layout-electric .mobile-nav{background:var(--header)}.layout-salon .service-grid,.layout-garden .service-grid,.layout-electric .service-grid{grid-template-columns:1fr}.layout-salon .reviews,.layout-garden .reviews,.layout-electric .reviews{grid-template-columns:1fr}.layout-salon .gallery,.layout-garden .gallery,.layout-electric .gallery{grid-template-columns:1fr 1fr}.layout-salon .hero-copy,.layout-electric .hero-copy{padding:42px 18px 54px}.layout-salon .hero-title,.layout-electric .hero-title{font-size:44px!important}.layout-garden .hero{margin-top:68px}.layout-garden .brand-scene{height:560px}.layout-garden .hero-copy{padding:45px 0}.layout-garden .hero-copy .inner{width:calc(100% - 36px)}.layout-garden .hero-title{font-size:48px!important}}
  `;
}

function templateDesignMotion() { return ''; }
